### ISSUE TITLE
Update Tick.toString method

### ISSUE THREAD

**Issue by lequer** [mdeverdelhan/ta4j#37]
in Tick.toString method, we try to format a Decimal to a Double:
```java
java.util.IllegalFormatConversionException: f != eu.verdelhan.ta4j.Decimal
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
	at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2806)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2753)
	at java.util.Formatter.format(Formatter.java:2526)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2925)
	at eu.verdelhan.ta4j.Tick.toString(Tick.java:236)
```
```java
 @Override
    public String toString() {
        return String.format("[time: %1$td/%1$tm/%1$tY %1$tH:%1$tM:%1$tS, close price: %2$f]", endTime
                .toGregorianCalendar(), closePrice);
    }
````
Maybe closePrice should be replaced with closePrice.toDouble().
Thanks

**Comment by mdeverdelhan** [comment]
Thank you!
